{{- if .Values.caddy.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "remote-rag.fullname" . }}-caddy
  labels:
    app.kubernetes.io/name: {{ include "remote-rag.name" . }}-caddy
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "remote-rag.name" . }}-caddy
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "remote-rag.name" . }}-caddy
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: caddy
          image: "{{ .Values.caddy.image.repository }}:{{ .Values.caddy.image.tag }}"
          imagePullPolicy: {{ .Values.caddy.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: caddy-config
              mountPath: /etc/caddy/Caddyfile
              subPath: Caddyfile
      volumes:
        - name: caddy-config
          configMap:
            name: {{ include "remote-rag.fullname" . }}-caddy
{{- end }}
